[project]
name = "metodista"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "sqlalchemy>=2.0.43",
    "uvicorn[standard]>=0.37.0",
]
